version: "3"

services:
  db:
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: pandemic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pandemic
      MYSQL_PASSWORD: panedemic
    image: mysql:8.0.17
    ports:
      - "3326:3306"
    restart: always
    volumes:
      - ./.volumes/db:/var/lib/mysql
