version: "3"

services:
  db:
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: pandemic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pandemic
      MYSQL_PASSWORD: panedemic
    image: mysql:8.0.17
    ports:
      - "3326:3306"
    restart: always
    volumes:
      - ./.volumes/db:/var/lib/mysql
  frontends-slack:
    build: ./frontends-slack
    env_file: ./env/dev/frontends-slack.env
    environment:
      - DEBUG=1
    ports:
      - "6010:80"
    stdin_open: true
    tty: true
    volumes:
      - ./frontends-slack:/var/www
  services-slack:
    build: ./services-slack
    env_file: ./env/dev/services-slack.env
    environment:
      - DEBUG=1
    ports:
      - "6020:80"
    stdin_open: true
    tty: true
    volumes:
      - ./services-slack:/var/www
  ngrok:
    image: wernight/ngrok
    command: ngrok http frontends-slack:80
    ports:
      - "4040:4040"
