# Generated by Django 3.0.5 on 2020-04-19 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team_id", models.CharField(max_length=255)),
                ("bot_user_id", models.CharField(max_length=255)),
                ("bot_access_token", models.CharField(max_length=255)),
            ],
        ),
    ]
